#test ci
#watch changes and build
branches:
  only:
    - master
    - watch_pull_request_with_travis

language: java
jdk: 
  - oraclejdk8

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - mvn install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name “xxxx”
  - git config --local user.email “xxxx”
  - git tag “$(date +’%Y%m%d%H%M%S’)-$(git log --format=%h -1)”
deploy:
  provider: release
  api_key: $github_oauth_token
  file: /home/travis/.m2/repository/com/fc/hahu/1.3/hahu-1.3.war
  skip_cleanup: true
  on:
    branch: learn_github_releases
